/**
 * Google Calendar API integration (direct HTTP, no googleapis npm).
 *
 * ## Why direct fetch() instead of googleapis npm package?
 *
 *   - The `googleapis` npm package is ~12MB — enormous for TWO API calls.
 *   - We only need OAuth token refresh + event creation, both trivial HTTP.
 *   - Direct fetch() keeps our bundle lean and our dependency tree shallow.
 *   - Teaching value: understanding OAuth 2.0 flow without magic abstractions.
 *
 * ## Authentication flow
 *
 *   1. One-time manual setup: a CLI script obtains a refresh token via
 *      OAuth 2.0 consent flow.
 *   2. On every event creation, getAccessToken() exchanges the refresh
 *      token for a short-lived access token (1 hour).
 *   3. Google APIs use the access token as Bearer authorization.
 *
 * ## Google Meet conferencing
 *
 *   When creating an event, we pass `conferenceDataVersion: 1` and
 *   `conferenceData.createRequest` with a unique `requestId`. Google
 *   automatically generates a Meet link in the response.
 *
 *   requestId: a unique string (we use a UUID) that ensures idempotent
 *   Meet link creation — the same requestId always returns the same link.
 *
 * Environment variables used:
 *   - GOOGLE_CLIENT_ID      → OAuth 2.0 client ID
 *   - GOOGLE_CLIENT_SECRET  → OAuth 2.0 client secret
 *   - GOOGLE_REFRESH_TOKEN  → Long-lived refresh token (obtained once via CLI)
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const OAUTH_TOKEN_URL = "https://oauth2.googleapis.com/token";
const CALENDAR_API_BASE = "https://www.googleapis.com/calendar/v3";

// ---------------------------------------------------------------------------
// getAccessToken
// ---------------------------------------------------------------------------

/**
 * Exchanges a Google OAuth 2.0 refresh token for a short-lived access token.
 *
 * Access tokens expire after ~1 hour. We call this before every calendar
 * operation to ensure we always have a valid token. Google's refresh token
 * is long-lived (doesn't expire unless revoked), so this gives us persistent
 * API access without re-doing the OAuth consent flow.
 *
 * @param refreshToken - The stored refresh token (GOOGLE_REFRESH_TOKEN from env)
 * @param clientId     - Google OAuth client ID (GOOGLE_CLIENT_ID from env)
 * @param clientSecret - Google OAuth client secret (GOOGLE_CLIENT_SECRET from env)
 * @returns A fresh access token string
 * @throws If the token exchange fails (invalid credentials, revoked token, etc.)
 */
export async function getAccessToken(
  refreshToken: string,
  clientId: string,
  clientSecret: string
): Promise<string> {
  const response = await fetch(OAUTH_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      refresh_token: refreshToken,
      grant_type: "refresh_token",
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(
      `Google OAuth token refresh failed (${response.status}): ${errorBody}`
    );
  }

  const data = (await response.json()) as { access_token: string };
  return data.access_token;
}

// ---------------------------------------------------------------------------
// createEvent
// ---------------------------------------------------------------------------

/**
 * Creates a Google Calendar event with automatic Google Meet conferencing.
 *
 * The event is created on the authenticated user's primary calendar
 * (the one associated with the refresh token). Google Meet link is
 * automatically generated by passing `conferenceDataVersion: 1` and
 * a `createRequest` with a unique `requestId`.
 *
 * @param summary        - Event title (e.g., "Lectura General de Tarot — Cliente")
 * @param description    - Event description (customer name, service details)
 * @param startDateTime  - ISO 8601 start (e.g., "2026-05-10T14:00:00-05:00")
 * @param endDateTime    - ISO 8601 end
 * @param attendeeEmail  - Customer's email (added as attendee)
 * @param accessToken    - Valid Google OAuth access token (from getAccessToken)
 * @returns Object with { eventId, hangoutLink, htmlLink }
 */
export async function createEvent(
  summary: string,
  description: string,
  startDateTime: string,
  endDateTime: string,
  attendeeEmail: string,
  accessToken: string
): Promise<{ eventId: string; hangoutLink: string; htmlLink: string }> {
  // Unique requestId ensures Meet link creation is idempotent
  const requestId = crypto.randomUUID();

  const eventData = {
    summary,
    description,
    start: {
      dateTime: startDateTime,
      timeZone: "America/Bogota",
    },
    end: {
      dateTime: endDateTime,
      timeZone: "America/Bogota",
    },
    attendees: [{ email: attendeeEmail }],
    // Enable automatic Google Meet conference creation
    conferenceData: {
      createRequest: {
        requestId,
        conferenceSolutionKey: { type: "hangoutsMeet" },
      },
    },
  };

  const response = await fetch(
    `${CALENDAR_API_BASE}/calendars/primary/events?conferenceDataVersion=1`,
    {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(eventData),
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(
      `Google Calendar event creation failed (${response.status}): ${errorBody}`
    );
  }

  const data = (await response.json()) as {
    id: string;
    hangoutLink: string;
    htmlLink: string;
  };

  return {
    eventId: data.id,
    hangoutLink: data.hangoutLink,
    htmlLink: data.htmlLink,
  };
}
